# Check on http://lint.travis-ci.org/ after modifying! Taken and modified
# from https://github.com/biocore/scikit-bio/blob/master/.travis.yml
sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - export MPLBACKEND='Agg'
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -n st2 -c biocore python=$PYTHON_VERSION nose numpy scipy h5py flake8 scikit-bio seaborn
  - source activate st2
  - pip install coveralls
  - pip install .
script:
  - nosetests --with-coverage
  - flake8 sourcetracker setup.py
  - sourcetracker2 gibbs --help
  - sourcetracker2 gibbs -i data/tiny-test/otu_table.biom -m data/tiny-test/map.txt -o example1/ --restarts 2 --draws_per_restart 3 --burnin 10 --delay 2
  - sourcetracker2 gibbs -i data/tiny-test/otu_table.biom -m data/tiny-test/alt-map.txt -o example2/ --source_sink_column source-or-sink --source_column_value src --sink_column_value snk --source_category_column sample-type --restarts 2 --draws_per_restart 3 --burnin 10 --delay 2
  - sourcetracker2 gibbs -i data/tiny-test/otu_table.biom -m data/tiny-test/map.txt  --loo -o example3/ --restarts 2 --draws_per_restart 3 --burnin 10 --delay 2
  - sourcetracker2 gibbs -i data/tiny-test/otu_table.biom -m data/tiny-test/map.txt  -o example4/ --burnin 25 --restarts 2 --draws_per_restart 3 --delay 2
  - sourcetracker2 gibbs -i data/tiny-test/otu_table.biom -m data/tiny-test/map.txt  -o example5/ --sink_rarefaction_depth 1700 --source_rarefaction_depth 1500 --restarts 2 --draws_per_restart 3 --burnin 10 --delay 2
after_success:
  - coveralls
